
server:
  port: 8080
  address: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inter?characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Hzhym1996
    driver-class-name: com.mysql.cj.jdbc.Driver

