
server:
  port: 8080
  address: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://localhost3306/intership?characterEncoding=UFT8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

